// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginRequest.proto

package com.yzh.requestrespose.request;

public final class LoginRequest {
  private LoginRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginRequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginRequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string phone = 1;</code>
     */
    String getPhone();
    /**
     * <code>optional string phone = 1;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>optional string password = 2;</code>
     */
    String getPassword();
    /**
     * <code>optional string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional .LoginRequestMessage.PhoneType phoneType = 3;</code>
     */
    int getPhoneTypeValue();
    /**
     * <code>optional .LoginRequestMessage.PhoneType phoneType = 3;</code>
     */
    com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.PhoneType getPhoneType();
  }
  /**
   * Protobuf type {@code LoginRequestMessage}
   */
  public  static final class LoginRequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginRequestMessage)
      LoginRequestMessageOrBuilder {
    // Use LoginRequestMessage.newBuilder() to construct.
    private LoginRequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginRequestMessage() {
      phone_ = "";
      password_ = "";
      phoneType_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoginRequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              phone_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              phoneType_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.requestrespose.request.LoginRequest.internal_static_LoginRequestMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.requestrespose.request.LoginRequest.internal_static_LoginRequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.class, com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code LoginRequestMessage.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>iPhone = 0;</code>
       */
      iPhone(0),
      /**
       * <code>AndroidPhone = 1;</code>
       */
      AndroidPhone(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>iPhone = 0;</code>
       */
      public static final int iPhone_VALUE = 0;
      /**
       * <code>AndroidPhone = 1;</code>
       */
      public static final int AndroidPhone_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static PhoneType valueOf(int value) {
        return forNumber(value);
      }

      public static PhoneType forNumber(int value) {
        switch (value) {
          case 0: return iPhone;
          case 1: return AndroidPhone;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PhoneType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneType[] VALUES = values();

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PhoneType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:LoginRequestMessage.PhoneType)
    }

    public static final int PHONE_FIELD_NUMBER = 1;
    private volatile Object phone_;
    /**
     * <code>optional string phone = 1;</code>
     */
    public String getPhone() {
      Object ref = phone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <code>optional string phone = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      Object ref = phone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile Object password_;
    /**
     * <code>optional string password = 2;</code>
     */
    public String getPassword() {
      Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONETYPE_FIELD_NUMBER = 3;
    private int phoneType_;
    /**
     * <code>optional .LoginRequestMessage.PhoneType phoneType = 3;</code>
     */
    public int getPhoneTypeValue() {
      return phoneType_;
    }
    /**
     * <code>optional .LoginRequestMessage.PhoneType phoneType = 3;</code>
     */
    public com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.PhoneType getPhoneType() {
      com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.PhoneType result = com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.PhoneType.valueOf(phoneType_);
      return result == null ? com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.PhoneType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, phone_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      if (phoneType_ != com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.PhoneType.iPhone.getNumber()) {
        output.writeEnum(3, phoneType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, phone_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      if (phoneType_ != com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.PhoneType.iPhone.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, phoneType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage)) {
        return super.equals(obj);
      }
      com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage other = (com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage) obj;

      boolean result = true;
      result = result && getPhone()
          .equals(other.getPhone());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && phoneType_ == other.phoneType_;
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + PHONETYPE_FIELD_NUMBER;
      hash = (53 * hash) + phoneType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginRequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginRequestMessage)
        com.yzh.requestrespose.request.LoginRequest.LoginRequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.requestrespose.request.LoginRequest.internal_static_LoginRequestMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.requestrespose.request.LoginRequest.internal_static_LoginRequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.class, com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.Builder.class);
      }

      // Construct using com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        phone_ = "";

        password_ = "";

        phoneType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.requestrespose.request.LoginRequest.internal_static_LoginRequestMessage_descriptor;
      }

      public com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage getDefaultInstanceForType() {
        return com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.getDefaultInstance();
      }

      public com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage build() {
        com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage buildPartial() {
        com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage result = new com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage(this);
        result.phone_ = phone_;
        result.password_ = password_;
        result.phoneType_ = phoneType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage) {
          return mergeFrom((com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage other) {
        if (other == com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.getDefaultInstance()) return this;
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (other.phoneType_ != 0) {
          setPhoneTypeValue(other.getPhoneTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object phone_ = "";
      /**
       * <code>optional string phone = 1;</code>
       */
      public String getPhone() {
        Object ref = phone_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string phone = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string phone = 1;</code>
       */
      public Builder setPhone(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 1;</code>
       */
      public Builder clearPhone() {

        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 1;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        phone_ = value;
        onChanged();
        return this;
      }

      private Object password_ = "";
      /**
       * <code>optional string password = 2;</code>
       */
      public String getPassword() {
        Object ref = password_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPassword(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder clearPassword() {

        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        password_ = value;
        onChanged();
        return this;
      }

      private int phoneType_ = 0;
      /**
       * <code>optional .LoginRequestMessage.PhoneType phoneType = 3;</code>
       */
      public int getPhoneTypeValue() {
        return phoneType_;
      }
      /**
       * <code>optional .LoginRequestMessage.PhoneType phoneType = 3;</code>
       */
      public Builder setPhoneTypeValue(int value) {
        phoneType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .LoginRequestMessage.PhoneType phoneType = 3;</code>
       */
      public com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.PhoneType getPhoneType() {
        com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.PhoneType result = com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.PhoneType.valueOf(phoneType_);
        return result == null ? com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.PhoneType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .LoginRequestMessage.PhoneType phoneType = 3;</code>
       */
      public Builder setPhoneType(com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage.PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        phoneType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .LoginRequestMessage.PhoneType phoneType = 3;</code>
       */
      public Builder clearPhoneType() {

        phoneType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:LoginRequestMessage)
    }

    // @@protoc_insertion_point(class_scope:LoginRequestMessage)
    private static final com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage();
    }

    public static com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginRequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<LoginRequestMessage>() {
      public LoginRequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginRequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginRequestMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LoginRequestMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.requestrespose.request.LoginRequest.LoginRequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRequestMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginRequestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022LoginRequest.proto\"\224\001\n\023LoginRequestMes" +
      "sage\022\r\n\005phone\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\0221\n" +
      "\tphoneType\030\003 \001(\0162\036.LoginRequestMessage.P" +
      "honeType\")\n\tPhoneType\022\n\n\006iPhone\020\000\022\020\n\014And" +
      "roidPhone\020\001B\'\n\027com.yzh.requestrespose.requestB\014" +
      "LoginRequestb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LoginRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginRequestMessage_descriptor,
        new String[] { "Phone", "Password", "PhoneType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
